### ISSUE TITLE
2017.0

### ISSUE THREAD

**Issue by dominichayesferen** [dominichayesferen/ferenOSProjectUpdates#3]
...and with that, LET THE DEVELOPMENT BEGIN!!

**Comment by feren** [comment]
Also, for those that didn't see it:
https://plus.google.com/+ffcovfn/posts/jPXC1yiJBrF

**Comment by dominichayesferen** [comment]
Also, for those that didn't see it:
![attach me](https://cloud.githubusercontent.com/assets/11057934/21944853/2eec8040-d9d0-11e6-86b3-318202f52ce3.png)

**Comment by dominichayesferen** [comment]
First Ever Screenshot:
- New Wallpapers
- New Themer
- Updated Themes
- New Launcher based on Slingshot
- MORE

![screenshot from 2017-01-15 19-38-12](https://cloud.githubusercontent.com/assets/11057934/21965561/80495b6c-db5a-11e6-86f9-5f4fd4e19972.png)
![screenshot from 2017-01-15 19-38-48](https://cloud.githubusercontent.com/assets/11057934/21965562/8049da42-db5a-11e6-9876-538e0653b661.png)

**Comment by dominichayesferen** [comment]
Sorry this place hasn't been updated for a long while, I actually forgot about this issue during 2017.0's Development, but, 2017.0's out, and this will be used to show the development of x32...
