### ISSUE TITLE
User/Group window too big for laptop

### ISSUE THREAD

**Issue by gman8321** [dominichayesferen/ferenOSProjectUpdates#5]
Dell Latitude E6510, 1440 x 900 resolution. From the control center when I go to Users/Groups, the window grow in size horizontally and it is impossible to see options at the bottom of the window. 
![screenshot from 2017-06-06 21-51-30](https://user-images.githubusercontent.com/7431553/26860209-59014ade-4b02-11e7-880c-a543e39ad448.png)

**Comment by dominichayesferen** [comment]
Yeah, that's an upstream bug with Linux Mint, I find it just as annoying TBH...

**Comment by dominichayesferen** [comment]
This just got fixed in Cinnamon's GitHub, you'll hopefully see the fix in LM 18.2 / feren OS 2017.1

**Comment by gman8321** [comment]
Great to hear. 





---- On Thu, 08 Jun 2017 11:14:21 -0500 feren CEO &lt;notifications@github.com&gt; wrote ----




This just got fixed in Cinnamon's GitHub, you'll hopefully see the fix in LM 18.2 / feren OS 2017.1
